# Generated by Django 6.0 on 2026-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
