# Generated by Django 6.0 on 2025-12-29 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', 'completed', '-created_at'], name='todo_user_completed_created'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['user', '-updated_at', '-created_at'], name='todo_user_updated_created'),
        ),
    ]
