# Generated by Django 6.0 on 2026-01-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todoitem_notes"),
        ("todo", "0002_todoitem_todo_user_completed_created_and_more"),
    ]

    operations = []
