"""
Django settings for django_todo project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent


# テスト実行時判定
TESTING: bool = "test" in sys.argv
DEV_SERVER: bool = "runserver" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
#
# - 本番は必ず False（=0）
# - 開発時は `manage.py runserver` のとき True をデフォルトにする（利便性）
# - 明示的に環境変数で上書き可能（優先順: DJANGO_DEBUG > DEBUG(旧) > runserver 判定）
def _env_bool(name: str, *, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    value = raw.strip().lower()
    if value in {"1", "true", "t", "yes", "y", "on"}:
        return True
    if value in {"0", "false", "f", "no", "n", "off"}:
        return False
    return default


DEBUG: bool = _env_bool(
    "DJANGO_DEBUG",
    default=_env_bool("DEBUG", default=DEV_SERVER),
)


# SECURITY WARNING: keep the secret key used in production secret!
# 本番では環境変数 DJANGO_SECRET_KEY を必ず設定すること
_DEFAULT_SECRET_KEY: str = "django-insecure-47vq$-9*n5s-+n)%1@x)355w!sxx(ctig---p%t#*&c#49_swr"
SECRET_KEY: str = os.getenv("DJANGO_SECRET_KEY", _DEFAULT_SECRET_KEY)

_DEBUG_WAS_EXPLICITLY_CONFIGURED: bool = os.getenv("DJANGO_DEBUG") is not None or os.getenv("DEBUG") is not None
_RUNNING_UNDER_GUNICORN: bool = any("gunicorn" in arg for arg in sys.argv)

# "DEBUG=False" だけでは開発中の管理コマンド実行（migrate等）でも該当してしまうため、
# 「本番に近い状況」（gunicorn起動 or 明示的にDEBUGを落としている）に限定して必須化する。
if (
    not DEBUG
    and not TESTING
    and (_RUNNING_UNDER_GUNICORN or _DEBUG_WAS_EXPLICITLY_CONFIGURED)
    and SECRET_KEY == _DEFAULT_SECRET_KEY
):
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set for production-like runs (DJANGO_DEBUG=0).")


def _split_csv(value: str) -> list[str]:
    """カンマ区切りの文字列をリストへ変換する。

    Args:
        value: カンマ区切り文字列。

    Returns:
        空要素を除去した文字列リスト。
    """

    return [item.strip() for item in value.split(",") if item.strip()]


# Host header validation
# 本番は環境変数 DJANGO_ALLOWED_HOSTS で明示指定する。
ALLOWED_HOSTS: list[str] = _split_csv(os.getenv("DJANGO_ALLOWED_HOSTS", ""))

# 開発・テスト時は未指定でもローカルアクセスしやすいデフォルトを許可する。
if not ALLOWED_HOSTS and (DEBUG or TESTING):
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
        "[::1]",
        "testserver",
    ]


# Application definition

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "info",
    "todo",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 静的ファイル配信
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF: str = "django_todo.urls"

TEMPLATES: list[dict[str, object]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION: str = "django_todo.wsgi.application"


# Cache
# 本番では Redis 等への差し替えを推奨（環境変数で上書き可）。
CACHES: dict[str, object] = {
    "default": {
        "BACKEND": os.getenv(
            "DJANGO_CACHE_BACKEND",
            "django.core.cache.backends.locmem.LocMemCache",
        ),
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 本番ではデータを /app/data に配置して永続化ボリュームにマウント


def _db_from_database_url(database_url: str) -> dict[str, object]:
    u = urlparse(database_url)
    qs = parse_qs(u.query)
    # postgres://user:pass@host:5432/dbname?sslmode=require
    # postgresql://user:pass@host:5432/dbname?sslmode=require
    sslmode = qs.get("sslmode", [""])[0] or os.getenv("PGSSLMODE", "prefer")
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": u.path.lstrip("/"),
        "USER": u.username or "",
        "PASSWORD": u.password or "",
        "HOST": u.hostname or "",
        "PORT": str(u.port or 5432),
        # 接続を使い回して速度・負荷を改善（0は毎回接続）
        "CONN_MAX_AGE": int(os.getenv("DJANGO_CONN_MAX_AGE", "60")),
        # 外部DBはSSL必須のことが多い
        "OPTIONS": {
            "sslmode": sslmode,  # require にすることも多い
        },
    }


DATABASE_URL: str = os.getenv("DATABASE_URL", "")

if DATABASE_URL:
    DATABASES = {"default": _db_from_database_url(DATABASE_URL)}
else:
    _DB_PATH: Path = Path(os.getenv("DJANGO_DB_PATH", BASE_DIR / "db.sqlite3"))
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _DB_PATH,
            "OPTIONS": {
                "init_command": "PRAGMA journal_mode=WAL;",
                "timeout": 20,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, object]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE: str = "ja"

TIME_ZONE: str = "Asia/Tokyo"

USE_I18N: bool = True
USE_TZ: bool = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL: str = "static/"
STATICFILES_DIRS: list[Path] = [BASE_DIR / "templates" / "static"]

# collectstatic の出力先
STATIC_ROOT: Path = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: str = "django.db.models.BigAutoField"


# Todo
# 1ユーザーが保持できるTodo件数の上限。過度な蓄積や悪用を防ぐためのガード。
# 必要に応じて環境変数 TODO_MAX_ITEMS_PER_USER で上書きできる。
TODO_MAX_ITEMS_PER_USER: int = int(os.getenv("TODO_MAX_ITEMS_PER_USER", "200"))


# Authentication
LOGIN_URL: str = "/accounts/login/"
LOGIN_REDIRECT_URL: str = "/"
LOGOUT_REDIRECT_URL: str = "/accounts/login/"


# Signup
# ユーザー登録時の追加検証を設定する。
# 将来的に別の検証方式（reCAPTCHA等）に移行する場合は、このセクションと
# accounts/validators.py を変更することで対応可能。
#
# SIGNUP_VALIDATOR: 使用するバリデータクラスのパス
#   - "accounts.validators.InvitationCodeValidator": 招待コード方式（デフォルト）
#   - "accounts.validators.NoOpValidator": 検証なし（オープン登録）
# SIGNUP_INVITATION_CODE: 招待コード方式で使用する正解コード（環境変数推奨）
SIGNUP_VALIDATOR: str = os.getenv(
    "SIGNUP_VALIDATOR",
    "accounts.validators.InvitationCodeValidator",
)
SIGNUP_INVITATION_CODE: str = os.getenv("SIGNUP_INVITATION_CODE", "")


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/


LOG_DIR: Path = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING: dict[str, object] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} {module}.{funcName}:{lineno} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": "CRITICAL" if TESTING else "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "app.log",
            "maxBytes": 5 * 1024 * 1024,  # 5MB
            "backupCount": 3,  # 最大3世代保持
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "todo": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# ===========================================
# 本番セキュリティ設定
# ===========================================
if not DEBUG:
    # HTTPS設定
    SECURE_PROXY_SSL_HEADER: tuple[str, str] = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )
    SECURE_SSL_REDIRECT: bool = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "0") == "1"

    # セッション・クッキー設定
    SESSION_COOKIE_SECURE: bool = True
    CSRF_COOKIE_SECURE: bool = True
    SESSION_COOKIE_HTTPONLY: bool = True

    # HSTS設定（HTTPSを強制）
    SECURE_HSTS_SECONDS: int = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS: bool = True
    SECURE_HSTS_PRELOAD: bool = True

    # その他セキュリティヘッダー
    SECURE_CONTENT_TYPE_NOSNIFF: bool = True
    X_FRAME_OPTIONS: str = "DENY"

    # CSRF信頼オリジン（リバースプロキシ経由の場合に必要）
    _csrf_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
    if _csrf_origins:
        CSRF_TRUSTED_ORIGINS: list[str] = _split_csv(_csrf_origins)
