"""
Django settings for django_todo project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent


# テスト実行時判定
TESTING: bool = "test" in sys.argv


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 本番では環境変数 DJANGO_SECRET_KEY を必ず設定すること
SECRET_KEY: str = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-47vq$-9*n5s-+n)%1@x)355w!sxx(ctig---p%t#*&c#49_swr",
)

# SECURITY WARNING: don't run with debug turned on in production!
# 本番では環境変数 DJANGO_DEBUG=0 を設定
DEBUG: bool = os.getenv("DJANGO_DEBUG", "1") == "1"


def _split_csv(value: str) -> list[str]:
    """カンマ区切りの文字列をリストへ変換する。

    Args:
        value: カンマ区切り文字列。

    Returns:
        空要素を除去した文字列リスト。
    """

    return [item.strip() for item in value.split(",") if item.strip()]


# Host header validation
# 本番は環境変数 DJANGO_ALLOWED_HOSTS で明示指定する。
ALLOWED_HOSTS: list[str] = _split_csv(os.getenv("DJANGO_ALLOWED_HOSTS", ""))

# 開発・テスト時は未指定でもローカルアクセスしやすいデフォルトを許可する。
if not ALLOWED_HOSTS and (DEBUG or TESTING):
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
        "[::1]",
        "testserver",
    ]


# Application definition

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "todo",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # 静的ファイル配信
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF: str = "django_todo.urls"

TEMPLATES: list[dict[str, object]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION: str = "django_todo.wsgi.application"


# Cache
# 本番では Redis 等への差し替えを推奨（環境変数で上書き可）。
CACHES: dict[str, object] = {
    "default": {
        "BACKEND": os.getenv(
            "DJANGO_CACHE_BACKEND",
            "django.core.cache.backends.locmem.LocMemCache",
        ),
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 本番ではデータを /app/data に配置して永続化ボリュームにマウント

_DB_PATH: Path = Path(os.getenv("DJANGO_DB_PATH", BASE_DIR / "db.sqlite3"))

DATABASES: dict[str, object] = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _DB_PATH,
        "OPTIONS": {
            # WALモードで並行アクセスを改善
            "init_command": "PRAGMA journal_mode=WAL;",
            "timeout": 20,  # ロック待機時間（秒）
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, object]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE: str = "ja"

TIME_ZONE: str = "Asia/Tokyo"

USE_I18N: bool = True
USE_TZ: bool = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL: str = "static/"
STATICFILES_DIRS: list[Path] = [BASE_DIR / "templates" / "static"]

# collectstatic の出力先
STATIC_ROOT: Path = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: str = "django.db.models.BigAutoField"


# Todo
# 1ユーザーが保持できるTodo件数の上限。過度な蓄積や悪用を防ぐためのガード。
# 必要に応じて環境変数 TODO_MAX_ITEMS_PER_USER で上書きできる。
TODO_MAX_ITEMS_PER_USER: int = int(os.getenv("TODO_MAX_ITEMS_PER_USER", "200"))


# Authentication
LOGIN_URL: str = "/accounts/login/"
LOGIN_REDIRECT_URL: str = "/"
LOGOUT_REDIRECT_URL: str = "/accounts/login/"


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/


LOG_DIR: Path = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING: dict[str, object] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} {module}.{funcName}:{lineno} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "level": "CRITICAL" if TESTING else "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "app.log",
            "maxBytes": 5 * 1024 * 1024,  # 5MB
            "backupCount": 3,  # 最大3世代保持
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "todo": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# ===========================================
# 本番セキュリティ設定
# ===========================================
if not DEBUG:
    # HTTPS設定
    SECURE_PROXY_SSL_HEADER: tuple[str, str] = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT: bool = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "0") == "1"

    # セッション・クッキー設定
    SESSION_COOKIE_SECURE: bool = True
    CSRF_COOKIE_SECURE: bool = True
    SESSION_COOKIE_HTTPONLY: bool = True

    # HSTS設定（HTTPSを強制）
    SECURE_HSTS_SECONDS: int = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS: bool = True
    SECURE_HSTS_PRELOAD: bool = True

    # その他セキュリティヘッダー
    SECURE_CONTENT_TYPE_NOSNIFF: bool = True
    X_FRAME_OPTIONS: str = "DENY"

    # CSRF信頼オリジン（リバースプロキシ経由の場合に必要）
    _csrf_origins = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
    if _csrf_origins:
        CSRF_TRUSTED_ORIGINS: list[str] = _split_csv(_csrf_origins)

